### ISSUE TITLE
Core Dumped for older Intel CPU (Ivy Bridge)

### ISSUE THREAD

**Issue by ffrankmil** [kolibril13/blender_csv_import#2]
I am eager to try the CSV import , but I am running an older CPU that causes a crash. 

RuntimeWarning: Missing required CPU features.

The following required CPU features were not detected:
    avx2, fma, bmi1, bmi2, lzcnt, movbe
Continuing to use this version of Polars on this processor will likely result in a crash.
Install the `polars-lts-cpu` package instead of `polars` to run Polars with better compatibility.

Hint: If you are on an Apple ARM machine (e.g. M1) this is likely due to running Python under Rosetta.
It is recommended to install a native version of Python that does not run under Rosetta x86-64 emulation.

If you believe this warning to be a false positive, you can set the `POLARS_SKIP_CPU_CHECK` environment variable to bypass this check.

  warnings.warn(
Illegal instruction (core dumped)

**Comment by kolibril13** [comment]
thanks for the report.
Can you provide some more information about your setup:
1. What Operating System?
2. What CPU, GPU?
3. What Blender Version?

As mentioned in your error message, you can try to use 
https://pypi.org/project/polars-lts-cpu/#description

In order to do so, first uninstall polars from your blender python.
For that, open a scripting tab in blender, go to the text editor, paste this code and then run the script.
This will uninstall the polars version that I shiped with the csv_importer extension:
```
import subprocess
import sys

subprocess.check_call([sys.executable, "-m", "pip", "uninstall", "-y", "polars"])
```
next, you can install the other polars version (and databpy, which will be used to run the below snippet):
```py
import subprocess
import sys

subprocess.check_call([sys.executable, "-m", "pip", "install", "polars-lts-cpu"])
subprocess.check_call([sys.executable, "-m", "pip", "install", "databpy"])

```
now, run this script (if it fails, rename `polars` to `polars-lts-cpu`):  
```py
import polars as pl
import databpy as db
from io import StringIO
import numpy as np

csv_data = StringIO(
    """MyFloat,Is_Visible,Intensity
42.12,true,10
12.33,false,20
"""
)

# here's how you'd load a custom csv file
# import pathlib as Pathlib
# json_file = Pathlib.cwd() / "data.csv"


df = pl.read_csv(csv_data)

# Since we no longer have nested arrays as in read_json, there's no need to explode columns
vertices = np.zeros((len(df), 3), dtype=np.float32)
bob = db.create_bob(vertices, name="Hello CSV")

# Store each column as an attribute
# Note: .to_numpy() returns a 1D array, so we reshape to 2D if needed.
for col in df.columns:
    data = df[col].to_numpy().reshape(-1, 1)
    bob.store_named_attribute(data, col)

# Print the stored attributes
print(bob.named_attribute("MyFloat"))
print(bob.named_attribute("Is_Visible"))
print(bob.named_attribute("Intensity"))
```

**Comment by ffrankmil** [comment]
Thank you for the help!

1. Ubuntu 24.04, Kernel 6.8.0-51-generic
2. Intel i5-3450 with Nvidia 1060 GB 6GB with 535.183.01
3. Latest Blender 4.3.2 from snap 

**Step1**: uninstall works
** Step2** script executes but I get in the terminal 

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: polars-lts-cpu in ./.local/lib/python3.11/site-packages (1.17.1)

I have tried

import subprocess
import sys
import os

target = os.path.join(sys.prefix, 'lib', 'site-packages')

subprocess.check_call([sys.executable, "-m", "pip", "install", "polars-lts-cpu", "-t", target ])
subprocess.check_call([sys.executable, "-m", "pip", "install", "databpy", "-t", target ])

but Snap is read-only filesystem and I get  OSError: [Errno 30] Read-only file system: '/snap/blender/5673/4.3/python/lib/site-packages'

Can you check during installation which package to choose or allow for legacy cpus?

**Comment by kolibril13** [comment]
thanks for the infos.
This will be difficult for me to debug from remote, but here are some thoughts:
Can you install other packages (like matpltolib) via pip in blender?
Maybe you have to set permissions for that in blender first, but I'm not sure about that.
This could help: 
https://www.reddit.com/r/blenderhelp/comments/11hj3sl/install_python_modules_via_pip_for_blender/

> Can you check during installation which package to choose or allow for legacy cpus?

For add-ons, I already bundle all required packages within a zip file that is uploaded to the blender extension store.
Including packages for legacy cpus would be possible, but it would drastically increase the extension size (it's currently 30 MB, and e.g. https://pypi.org/project/polars-lts-cpu/0.14.13/#files is another 13 MB.)

**Comment by ffrankmil** [comment]
Yes, I could install any other package like matplotlib.

So, the problem is the package naming of polars and polars-lts-cpu mentioned here: https://github.com/unionai-oss/pandera/issues/1777

What did the trick for me now:

```
import subprocess
import sys

subprocess.check_call([sys.executable, "-m", "pip", "uninstall", "-y", "polars"])
subprocess.check_call([sys.executable, "-m", "pip", "uninstall", "-y", "polars-lts-cpu"])
subprocess.check_call([sys.executable, "-m", "pip", "install", "polars-lts-cpu"])

```
and then it 
`import polars`

works, core dump solved and I could reactivate the package and load successfully CSVs.

**Comment by kolibril13** [comment]
Glad the script works now!
Does this work in the extension as well?

I'm closing this issue as this seems to be resolved.

**Comment by ffrankmil** [comment]
Yes, the extension works now.
